const express = require('express');
const router = express.Router();
const { db } = require('../config/firebase');

/**
 * GET /api/notifications
 * Fetches the alert history generated by the Lab Watchdog.
 */
router.get('/notifications', async (req, res) => {
  try {
    const snapshot = await db.collection('notifications')
      .orderBy('timestamp', 'desc')
      .limit(25) // Increased limit slightly for better history tracking
      .get();

    const alerts = snapshot.docs.map(doc => {
      const data = doc.data();
      const timestamp = data.timestamp ? data.timestamp.toDate() : new Date();
      
      // Logic: Show time if today, show date if older
      const isToday = new Date().toDateString() === timestamp.toDateString();
      
      const formattedTime = isToday 
        ? timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        : timestamp.toLocaleDateString([], { month: 'short', day: 'numeric' });

      return {
        id: doc.id,
        // Matches Watchdog 'title'
        title: data.title || "Sensor Alert",
        // Matches Watchdog 'detail'
        detail: data.detail || data.message || "Threshold breach detected.",
        time: formattedTime,
        // Raw timestamp for front-end sorting if needed
        rawTimestamp: timestamp 
      };
    });

    res.json(alerts);
  } catch (error) {
    console.error("Notifications Fetch Error:", error);
    res.status(500).json({ error: "Failed to load lab alert history." });
  }
});

/**
 * DELETE /api/notifications/clear
 * Optional: Endpoint to clear notification history from the app
 */
router.delete('/notifications/clear', async (req, res) => {
    try {
        const batch = db.batch();
        const snapshot = await db.collection('notifications').get();
        snapshot.docs.forEach((doc) => {
            batch.delete(doc.ref);
        });
        await batch.commit();
        res.json({ success: true, message: "Notification history cleared." });
    } catch (error) {
        res.status(500).json({ error: "Failed to clear history." });
    }
});

module.exports = router;